os: linux
dist: trusty
sudo: required

# Language used
language: python
python:
  - 3.6.5
cache: pip

# Install dependencies
install:
  - pip install pip --upgrade 
  - pip install -r requirements.txt

before_script:
  - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bandit .
  - flake8 .

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - codecov

env:
  global:
    - CC_TEST_REPORTER_ID=38209673480d024ecef218e64b24da89a39c51ece937266d308f5493fc25bcf8
